parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Binding des interfaces vers les implémentations
    App\Interfaces\Services\Ligne\LigneServiceInterface: '@App\Service\Ligne\LigneService'
    App\Interfaces\Repositories\Ligne\LigneRepositoryInterface: '@App\Repository\Ligne\LigneRepository'
    App\Interfaces\Services\Arret\ArretServiceInterface: '@App\Service\Arret\ArretService'
    App\Interfaces\Repositories\Arret\ArretRepositoryInterface: '@App\Repository\Arret\ArretRepository'

